# apiVersion: apps/v1beta1
# kind: Deployment
# metadata:
#   name: frontend
# spec:
#   template:
#     metadata:
#       labels:
#         app: frontend
#     spec:
#       containers:
#       - name: frontend
#         image: maduflavins/spleetfrontend
#         ports:
#         - containerPort: 3001
#         env:
#         - name: NODE_ENV
#           value: production
#         - name: REACT_APP_DOMAIN
#           valueFrom:
#             secretKeyRef:
#               name: frontend-secret-config
#               key: reactappui
#         - name: REACT_APP_CLIENT_ID
#           valueFrom:
#             secretKeyRef:
#               name: frontend-secret-config
#               key: clientid
#         - name: REACT_APP_AUDIENCE
#           valueFrom:
#             secretKeyRef:
#               name: frontend-secret-config
#               key: appaudience

apiVersion: apps/v1
kind: Deployment
metadata:
  name: spleetfrontend
  labels:
    app: spleetfrontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spleetfrontend
  template:
    metadata:
      labels:
        app: spleetfrontend
    spec:
      containers:
      - name: spleetfrontend
        image: maduflavins/spleetfrontend
        ports:
        - containerPort: 80
        env:
        - name: NODE_ENV
          value: production
        - name: REACT_APP_DOMAIN
          valueFrom:
            secretKeyRef:
              name: frontend-secret-config
              key: reactappui
        - name: REACT_APP_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: frontend-secret-config
              key: clientid
        - name: REACT_APP_AUDIENCE
          valueFrom:
            secretKeyRef:
              name: frontend-secret-config
              key: appaudience