apiVersion: v1
kind: Service
metadata:
  name: spleetfrontend
  namespace: default
  labels:
    app: spleetfrontend
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: http
      name: http
  selector:
    app: spleetfrontend